function Send-Alert {
    param (
        [Parameter(Mandatory)]
        [string]$Subject,
        [Parameter(Mandatory)]
        [string]$Message,
        [ValidateSet("Email", "Webhook", "EventLog")]
        [string[]]$Channels = @("EventLog"),
        [ValidateSet("Critical", "Warning", "Info")]
        [ValidateSet("Critical", "Warning", "Info")]
        [string]$Severity = "Info",
        [string[]]$Attachments = @(),
        [PSCustomObject]$Config = $null
    )
    
    # Load configuration if not provided
    if ($null -eq $Config) {
        try {
            if (Get-Command -Name Get-Configuration -ErrorAction SilentlyContinue) {
                $Config = Get-Configuration
            }
        }
        catch {
            # Configuration not available, continue without it
        }
    }

    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $hostname = $env:COMPUTERNAME

    Write-Host "[$timestamp] Sending $Severity alert: $Subject"

    # Event Log (always available)
    if ($Channels -contains "EventLog") {
        try {
            $eventMessage = @"
Subject: $Subject
Message: $Message
Severity: $Severity
Host: $hostname
Timestamp: $timestamp
"@
            Write-EventLog -LogName "Application" -Source "DAT" -EventId 1000 -EntryType $Severity -Message $eventMessage -ErrorAction Stop
            Write-Host "Alert logged to Event Log"
        }
        catch {
            # Create event source if it doesn't exist
            try {
                # Check if we are running as admin before attempting to create source
                $adminRole = [Security.Principal.WindowsBuiltInRole]::Administrator
                $isElevated = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole($adminRole)
                
                if ($isElevated) {
                    if (-not ([System.Diagnostics.EventLog]::SourceExists("DAT"))) {
                        New-EventLog -LogName "Application" -Source "DAT" -ErrorAction Stop
                    }
                    Write-EventLog -LogName "Application" -Source "DAT" -EventId 1000 -EntryType $Severity -Message $eventMessage
                    Write-Host "Alert logged to Event Log"
                }
                else {
                    Write-Warning "Could not write to Event Log: Source 'DAT' does not exist and script is not running as Administrator to create it."
                }
            }
            catch {
                Write-Warning "Could not write to Event Log: $_"
            }
        }
    }

    # Email alerts
    if ($Channels -contains "Email" -and $Config -and $Config.alerting.email) {
        try {
            $emailConfig = $Config.alerting.email

            # Load credentials if specified
            $credential = $null
            if ($emailConfig.credentialPath -and (Test-Path $emailConfig.credentialPath)) {
                $credential = Import-Clixml -Path $emailConfig.credentialPath
            }

            $emailParams = @{
                From        = if ($emailConfig.from) { $emailConfig.from } else { "DAT@$env:COMPUTERNAME" }
                To          = $emailConfig.to
                Subject     = "DAT Alert: $Subject"
                Body        = @"
DAT Alert - $Severity

Host: $hostname
Timestamp: $timestamp

$Message

This alert was generated by DAT (dag's Audit Tool).
"@
                SmtpServer  = $emailConfig.smtpServer
                Port        = if ($emailConfig.port) { $emailConfig.port } else { 25 }
                UseSsl      = $emailConfig.useSSL
                Attachments = $Attachments
            }

            if ($credential) {
                $emailParams.Credential = $credential
            }

            Send-MailMessage @emailParams
            Write-Host "Alert sent via Email"
        }
        catch {
            Write-Error "Failed to send email alert: $_"
        }
    }

    # Webhook alerts (Slack, Teams, Discord, Custom)
    if ($Channels -contains "Webhook" -and $Config -and $Config.alerting.webhook.url) {
        try {
            $webhookConfig = $Config.alerting.webhook
            $webhookUrl = $webhookConfig.url
            
            # Detect webhook type and format payload accordingly
            $payload = $null
            
            if ($webhookUrl -match "discord\.com") {
                # Discord webhook format
                $embedColor = switch ($Severity) {
                    "Critical" { 15158332 }  # Red
                    "Warning" { 16776960 }   # Yellow
                    default { 3066993 }      # Blue
                }
                
                # Truncate message to 4000 chars to be safe (limit is 4096)
                $safeMessage = if ($Message.Length -gt 4000) { $Message.Substring(0, 4000) + "... (truncated)" } else { $Message }

                $payload = @{
                    username   = "DAT Audit Tool"
                    avatar_url = "https://i.imgur.com/4M34hi2.png"
                    embeds     = @(
                        @{
                            title       = "DAT Alert - $Severity"
                            description = $safeMessage
                            color       = $embedColor
                            fields      = @(
                                @{
                                    name   = "Host"
                                    value  = $hostname
                                    inline = $true
                                },
                                @{
                                    name   = "Severity"
                                    value  = $Severity
                                    inline = $true
                                },
                                @{
                                    name   = "Timestamp"
                                    value  = $timestamp
                                    inline = $true
                                }
                            )
                            footer      = @{
                                text = "DAT - Desktop Audit Tool"
                            }
                            timestamp   = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ss.fffZ")
                        }
                    )
                } | ConvertTo-Json -Depth 10
                
            }
            elseif ($webhookUrl -match "slack\.com") {
                # Slack webhook format
                $payload = @{
                    text        = "DAT Alert - $Severity"
                    attachments = @(
                        @{
                            color  = switch ($Severity) {
                                "Critical" { "danger" }
                                "Warning" { "warning" }
                                default { "good" }
                            }
                            fields = @(
                                @{
                                    title = "Subject"
                                    value = $Subject
                                    short = $true
                                },
                                @{
                                    title = "Host"
                                    value = $hostname
                                    short = $true
                                },
                                @{
                                    title = "Timestamp"
                                    value = $timestamp
                                    short = $true
                                }
                            )
                            text   = $Message
                        }
                    )
                } | ConvertTo-Json -Depth 4
                
            }
            elseif ($webhookUrl -match "office\.com|outlook\.com") {
                # Microsoft Teams webhook format
                $themeColor = switch ($Severity) {
                    "Critical" { "FF0000" }
                    "Warning" { "FFA500" }
                    default { "0078D7" }
                }
                
                $payload = @{
                    "@type"    = "MessageCard"
                    "@context" = "https://schema.org/extensions"
                    summary    = "DAT Alert - $Severity"
                    themeColor = $themeColor
                    title      = "DAT Alert - $Severity"
                    sections   = @(
                        @{
                            activityTitle    = $Subject
                            activitySubtitle = $timestamp
                            facts            = @(
                                @{
                                    name  = "Host"
                                    value = $hostname
                                },
                                @{
                                    name  = "Severity"
                                    value = $Severity
                                },
                                @{
                                    name  = "Message"
                                    value = $Message
                                }
                            )
                        }
                    )
                } | ConvertTo-Json -Depth 4
                
            }
            else {
                # Generic webhook format
                $payload = @{
                    subject   = $Subject
                    message   = $Message
                    severity  = $Severity
                    host      = $hostname
                    timestamp = $timestamp
                } | ConvertTo-Json -Depth 4
            }

            $method = if ($webhookConfig.method) { $webhookConfig.method } else { "Post" }
            
            # Debug logging for webhook payload
            Write-Host "DEBUG: Webhook Payload: $payload"
            
            # Force UTF-8 encoding for the payload to handle emojis correctly
            # Force UTF-8 encoding for the payload to handle emojis correctly
            $utf8Payload = [System.Text.Encoding]::UTF8.GetBytes($payload)
            
            if ($Attachments -and $webhookUrl -match "discord\.com") {
                # Use HttpClient for multipart/form-data upload to Discord
                try {
                    Add-Type -AssemblyName System.Net.Http
                    $httpClient = New-Object System.Net.Http.HttpClient
                    $content = New-Object System.Net.Http.MultipartFormDataContent
                    
                    # Add JSON payload
                    $jsonContent = New-Object System.Net.Http.ByteArrayContent(, $utf8Payload)
                    $jsonContent.Headers.ContentType = [System.Net.Http.Headers.MediaTypeHeaderValue]::Parse("application/json")
                    $content.Add($jsonContent, "payload_json")
                    
                    # Add Files
                    $fileIndex = 0
                    foreach ($file in $Attachments) {
                        if (Test-Path $file) {
                            $fileBytes = [System.IO.File]::ReadAllBytes($file)
                            $fileContent = New-Object System.Net.Http.ByteArrayContent(, $fileBytes)
                            $fileName = Split-Path $file -Leaf
                            $content.Add($fileContent, "files[$fileIndex]", $fileName)
                            $fileIndex++
                        }
                    }
                    
                    $response = $httpClient.PostAsync($webhookUrl, $content).Result
                    if (-not $response.IsSuccessStatusCode) {
                        throw "Discord upload failed: $($response.StatusCode)"
                    }
                    Write-Host "Alert sent via Webhook (with attachments)"
                }
                catch {
                    Write-Error "Failed to send webhook with attachments: $_"
                    # Fallback to normal send without attachments if upload fails
                    Invoke-RestMethod -Uri $webhookUrl -Method $method -Body $utf8Payload -ContentType "application/json; charset=utf-8"
                }
                finally {
                    if ($httpClient) { $httpClient.Dispose() }
                    if ($content) { $content.Dispose() }
                }
            }
            else {
                # Standard JSON payload for non-Discord or no-attachment calls
                Invoke-RestMethod -Uri $webhookUrl -Method $method -Body $utf8Payload -ContentType "application/json; charset=utf-8"
                Write-Host "Alert sent via Webhook"
            }
        }
        catch {
            Write-Error "Failed to send webhook alert: $_"
        }
    }
}

function Test-AlertSystem {
    param (
        [PSCustomObject]$Config = $null
    )
    
    # Load configuration if not provided
    if ($null -eq $Config) {
        try {
            if (Get-Command -Name Get-Configuration -ErrorAction SilentlyContinue) {
                $Config = Get-Configuration
            }
        }
        catch {
            # Configuration not available
        }
    }

    Write-Host "Testing alert system..."

    # Test Event Log
    Send-Alert -Subject "Test Alert" -Message "This is a test alert from DAT" -Channels "EventLog" -Severity "Info"

    # Test Email if configured
    if ($Config -and $Config.alerting.enabled -and $Config.alerting.email) {
        Send-Alert -Subject "Test Email Alert" -Message "This is a test email alert from DAT" -Channels "Email" -Severity "Info" -Config $Config
    }

    # Test Webhook if configured
    if ($Config -and $Config.alerting.enabled -and $Config.alerting.webhook.url) {
        Send-Alert -Subject "Test Webhook Alert" -Message "This is a test webhook alert from DAT" -Channels "Webhook" -Severity "Info" -Config $Config
    }

    Write-Host "Alert system test completed"
}

# Standalone execution example
# To test: .\Send-Alert.ps1
# Or: Send-Alert -Subject "Test" -Message "Test message" -Channels EventLog -Severity Info
